import type { Events } from "$components/events/event";

const year: number = 2023;

export const term: string = "Michaelmas";

export const termcard: Events<"jcr" | "society"> = [
    {
        description: "'When I Grow Up, I Want to Be' Bop",
        date: [year, 10, 6],
        time: [21, 30],
        duration: [2, 30],
        location: "Function Room",
        type: "jcr",
    },
    {
        description: "Alt Bop",
        date: [year, 10, 6],
        time: [21, 30],
        duration: [2, 30],
        location: "Lloyd Room",
        type: "jcr",
    },
    {
        description: "CCMS: Freshers' Concert",
        date: [year, 10, 9],
        time: [18, 0],
        duration: [2, 0],
        location: "Chapel",
        type: "society",
    },
    {
        description: "CCMS x JCR World Mental Health Day Charity Formal (Theme: Green)",
        date: [year, 10, 11],
        time: [19, 30],
        duration: [2, 0],
        location: "Formal Hall",
        type: "jcr",
    },
    {
        description: "Y2K Super Bop",
        date: [year, 10, 12],
        time: [22, 30],
        duration: [3, 30],
        location: "Vinyl",
        type: "jcr",
    },
    {
        description: "CCMS: Inaugural Concert for Bill Fitzgerald Music Room",
        date: [year, 10, 13],
        time: [18, 0],
        duration: [2, 0],
        location: "Bill Fitzgerald Music Room",
        type: "society",
    },
    {
        description: "Charity Plant Sale",
        date: [year, 10, 15],
        time: [14, 0],
        duration: [1, 0],
        location: "JCR",
        type: "jcr",
    },
    {
        description: "LGBTQ+ Charity Dinner with Sandi Toksvig",
        date: [year, 10, 20],
        time: [19, 30],
        duration: [2, 0],
        location: "Formal Hall",
        type: "jcr",
    },
    {
        description: "CCMS: Sumei Bao-Smith - Bernstein Songs Recital",
        date: [year, 10, 20],
        time: [18, 0],
        duration: [1, 0],
        location: "Chapel",
        type: "society",
    },
    {
        description: "Halloween Super Bop",
        date: [year, 10, 27],
        time: [22, 30],
        duration: [3, 30],
        location: "Lola's",
        type: "jcr",
    },
    {
        description: "Animal Therapy",
        date: [year, 10, 28],
        time: [13, 0],
        duration: [2, 0],
        location: "Buttery",
        type: "jcr",
    },
    {
        description: "Rugby World Cup Grand Final Screening",
        date: [year, 10, 28],
        time: [20, 0],
        duration: [2, 0],
        location: "Buttery",
        type: "jcr",
    },
    {
        description: "Pumpkin Carving Competition",
        date: [year, 10, 31],
        time: [19, 0],
        duration: [2, 0],
        location: "JCR",
        type: "jcr",
    },
    {
        description: "CCMS: Aidan Módica - Piano Recital",
        date: [year, 11, 3],
        time: [18, 0],
        duration: [1, 0],
        location: "Bill Fitzgerald Music Room",
        type: "society",
    },
    {
        description: "CCMS: Week 5 Blues (Date & Time TBC)",
        date: [year, 11, 4],
        time: [20, 0],
        duration: [2, 0],
        location: "TBD",
        type: "society",
    },
    {
        description: "Week 5 Blues Film Night",
        date: [year, 11, 5],
        time: [20, 0],
        duration: [3, 0],
        location: "TV Room",
        type: "jcr",
    },
    {
        description: "CCMS: Qinglan Du - Vocal Recital",
        date: [year, 11, 10],
        time: [18, 0],
        duration: [1, 0],
        location: "Chapel",
        type: "society",
    },
    {
        description: "Karaoke",
        date: [year, 11, 12],
        time: [19, 0],
        duration: [2, 0],
        location: "Buttery",
        type: "jcr",
    },
    {
        description: "CCMS: Jack Robinson - Piano Recital",
        date: [year, 11, 17],
        time: [18, 0],
        duration: [1, 0],
        location: "Bill Fitzgerald Music Room",
        type: "society",
    },
    {
        description: "CCMS: Emily Sparkes - 'An Ode to Musicals' Recital",
        date: [year, 11, 24],
        time: [18, 0],
        duration: [1, 0],
        location: "Chapel",
        type: "society",
    },
    {
        description: "Bridgemas Eve",
        date: [year, 11, 24],
        time: [20, 30],
        duration: [2, 0],
        location: "Buttery",
        type: "jcr",
    },
    {
        description: "CCMS: Christmas Concert",
        date: [year, 11, 25],
        time: [19, 0],
        duration: [2, 0],
        location: "Chapel",
        type: "society",
    },
    {
        description: "Bridgemas Super Bop",
        date: [year, 11, 28],
        time: [22, 30],
        duration: [3, 30],
        location: "Lola's",
        type: "jcr",
    },
    {
        description: "Final Bop (Theme TBD)",
        date: [year, 11, 30],
        time: [21, 30],
        duration: [2, 30],
        location: "Function Room",
        type: "jcr",
    },
];
