import type { Events } from "$components/events/event";

const year: number = 2024;

export const term: string = "Lent";

/* TBC events: 
week2  LGBT social
*/
export const termcard: Events<"jcr" | "society"> = [
    {
        description: "'Spotify Wrapped' Bop",
        date: [year, 1, 19],
        time: [21, 30],
        duration: [3, 0],
        location: "Function Room",
        type: "jcr",
    },
    {
        description: "Art Soc: Oil Pastels",
        date: [year, 1, 20],
        time: [14, 0],
        duration: [2, 0],
        location: "TBC",
        type: "society",
    },
    {
        description: "Welfare Just Dance Party",
        date: [year, 1, 22],
        time: [17, 30],
        duration: [2, 0],
        location: "TV Room",
        type: "jcr",
    },
    {
        description: "Art Soc: Tie Dying",
        date: [year, 1, 27],
        time: [14, 0],
        duration: [2, 0],
        location: "TBC",
        type: "society",
    },
    {
        description: "Christ's May Ball Launch Party",
        date: [year, 1, 31],
        time: [19, 30],
        duration: [4, 0],
        location: "Formal Hall & Revs",
        type: "jcr",
    },
    {
        description: "Darwin Soc Talk by Dr. Alexander Jones",
        date: [year, 2, 1],
        time: [18, 0],
        duration: [1, 0],
        location: "TBC",
        type: "society",
    },
    {
        description: "Aidan Módica - Piano Recital",
        date: [year, 2, 2],
        time: [18, 0],
        duration: [1, 0],
        location: "Chapel",
        type: "society",
    },
    {
        description: "Welfare Movie Night",
        date: [year, 2, 2],
        time: [19, 30],
        duration: [2, 0],
        location: "TV Room",
        type: "jcr",
    },
    {
        description: "Art Soc: Wire & Clay Sculpting",
        date: [year, 2, 3],
        time: [14, 0],
        duration: [2, 0],
        location: "TBC",
        type: "society",
    },
    {
        description: "Parents' Formal",
        date: [year, 2, 3],
        time: [19, 30],
        duration: [2, 0],
        location: "Formal Hall",
        type: "jcr",
    },
    {
        description: "András Droppa",
        date: [year, 2, 3],
        time: [21, 0],
        duration: [2, 0],
        location: "Function Room",
        type: "society",
    },
    {
        description: "Halfway Hall",
        date: [year, 2, 5],
        time: [19, 30],
        duration: [2, 0],
        location: "Formal Hall",
        type: "jcr",
    },
    {
        description: "Movie Night",
        date: [year, 2, 6],
        time: [19, 30],
        duration: [2, 30],
        location: "TV Room",
        type: "jcr",
    },
    {
        description: "Pink Week Charity Hall",
        date: [year, 2, 7],
        time: [19, 30],
        duration: [2, 0],
        location: "Formal Mouse",
        type: "jcr",
    },
    {
        description: "Karaoke",
        date: [year, 2, 8],
        time: [19, 30],
        duration: [2, 30],
        location: "Buttery",
        type: "jcr",
    },
    {
        description: "Isaac Chan & Emily Long - Oboe & Piano Recital",
        date: [year, 2, 9],
        time: [18, 0],
        duration: [1, 0],
        location: "Chapel",
        type: "society",
    },
    {
        description: "Art Soc: Card/Flower Making",
        date: [year, 2, 10],
        time: [14, 0],
        duration: [2, 0],
        location: "TBC",
        type: "society",
    },
    {
        description: "LGBT x Disability Social (time TBC)",
        date: [year, 2, 10],
        time: [14, 0],
        duration: [2, 0],
        location: "TBC",
        type: "jcr",
    },
    {
        description: "Parents' Formal",
        date: [year, 2, 10],
        time: [19, 30],
        duration: [2, 0],
        location: "Formal Hall",
        type: "jcr",
    },
    {
        description: "Darwin Day",
        date: [year, 2, 12],
        time: [18, 0],
        duration: [1, 0],
        location: "TBC",
        type: "society",
    },
    {
        description: "Flora Clapham - Violin Recital",
        date: [year, 2, 16],
        time: [18, 0],
        duration: [2, 0],
        location: "Chapel",
        type: "society",
    },
    {
        description: "Parents' Formal",
        date: [year, 2, 17],
        time: [19, 30],
        duration: [2, 0],
        location: "Formal Hall",
        type: "jcr",
    },
    {
        description: "Bach's Magnificat Recital",
        date: [year, 2, 23],
        time: [18, 0],
        duration: [1, 0],
        location: "Chapel",
        type: "society",
    },
    {
        description: "Art Soc: Acrylic Painting",
        date: [year, 2, 24],
        time: [14, 0],
        duration: [2, 0],
        location: "TBC",
        type: "society",
    },
    {
        description: "Darwin Soc Movie Night (time TBC)",
        date: [year, 2, 25],
        time: [19, 0],
        duration: [2, 0],
        location: "TV Room",
        type: "society",
    },
    {
        description: "Choral Scholars' Recital",
        date: [year, 3, 6],
        time: [20, 0],
        duration: [1, 0],
        location: "Chapel",
        type: "society",
    },
    {
        description: "Darwin Soc Formal Swap",
        date: [year, 3, 6],
        time: [19, 30],
        duration: [2, 0],
        location: "St.Catherine's College",
        type: "society",
    },
    {
        description: "Art Society: Acrylic Painting",
        date: [year, 2, 24],
        time: [14, 0],
        duration: [2, 0],
        location: "TBC",
        type: "society",
    },
    {
        description: "Daniel Liu - Piano Recital",
        date: [year, 3, 8],
        time: [18, 0],
        duration: [1, 0],
        location: "Chapel",
        type: "society",
    },
    {
        description: "Darwin Soc Stargazing Trip (time TBC)",
        date: [year, 3, 8],
        time: [20, 0],
        duration: [3, 0],
        location: "Institute of Astronomy",
        type: "society",
    },
    {
        description: "Art Soc: Scrunchie Making",
        date: [year, 3, 9],
        time: [14, 0],
        duration: [2, 0],
        location: "TBC",
        type: "society",
    },
    {
        description: "End of Term Concert",
        date: [year, 3, 9],
        time: [19, 0],
        duration: [2, 0],
        location: "Chapel",
        type: "society",
    },
    {
        description: "End of Term Bop (TBC)",
        date: [year, 3, 15],
        time: [21, 30],
        duration: [3, 0],
        location: "TBC",
        type: "jcr",
    },
    {
        description: "Darwin Soc Formal Swap",
        date: [year, 3, 14],
        time: [19, 30],
        duration: [2, 0],
        location: "Newnham College",
        type: "society",
    },
];
