import type { Events } from "$components/events/Calendar.svelte";

export const freshers: Events<"compulsory" | "optional"> = [
    // Saturday 1st
    {
        description: "Welcome Hub",
        date: [2022, 10, 1],
        time: [9, 0],
        duration: [4, 0],
        location: "Lloyd Room",
        type: "compulsory",
    },
    {
        description: "Afternoon Meeting with your Tutor",
        date: [2022, 10, 1],
        time: [14, 0],
        duration: [2, 0],
        location: "(see letter for exact time and location)",
        type: "compulsory",
    },
    {
        description: "JCR Welfare Talk",
        date: [2022, 10, 1],
        time: [17, 0],
        duration: [0, 45],
        location: "Hamied Theatre",
        type: "compulsory",
    },
    {
        description: "Folk / Pop Group",
        date: [2022, 10, 1],
        time: [18, 0],
        duration: [1, 0],
        location: "Buttery",
        type: "optional",
    },
    {
        description: "Welcome Dinner (casual wear)",
        date: [2022, 10, 1],
        time: [19, 30],
        duration: [1, 30],
        location: "Formal Hall",
        type: "compulsory",
    },
    {
        description: "Initial Impressions Mixer (dress as your initial)",
        date: [2022, 10, 1],
        time: [21, 0],
        duration: [2, 0],
        location: "Function Room",
        type: "optional",
    },
    // Sunday 2nd
    {
        description: "Optional Individual Matriculation Photos",
        date: [2022, 10, 2],
        time: [9, 0],
        duration: [2, 45],
        location: "Portrait Room",
        type: "optional",
    },
    {
        description: "Group Matriculation Photo",
        date: [2022, 10, 2],
        time: [11, 45],
        duration: [1, 15],
        location: "Fellows' Garden",
        type: "compulsory",
    },
    {
        description: "Academic Events",
        date: [2022, 10, 2],
        time: [14, 0],
        duration: [3, 30],
        location: "Hamied Theatre",
        type: "compulsory",
    },
    {
        description: "Freshers' Chapel Service",
        date: [2022, 10, 2],
        time: [18, 0],
        duration: [0, 45],
        location: "Fellows' Garden",
        type: "optional",
    },
    {
        description: "Inter-College Mixer (with King's)",
        date: [2022, 10, 2],
        time: [19, 45],
        duration: [3, 15],
        location: "Location TBD",
        type: "optional",
    },
    {
        description: "Games and Chill (Uno Tournament)",
        date: [2022, 10, 2],
        time: [19, 45],
        duration: [3, 15],
        location: "JCR",
        type: "optional",
    },
    // Monday 3rd
    {
        description: "Meeting with Director of Studies",
        date: [2022, 10, 3],
        time: [9, 0],
        duration: [3, 0],
        location: "(actual time and location to be found on the Screens)",
        type: "compulsory",
    },
    {
        description: "Matriculation Register (names A-K)",
        date: [2022, 10, 3],
        time: [12, 0],
        duration: [1, 30],
        location: "Portrait Room",
        type: "compulsory",
    },
    {
        description: "Matriculation Register (names L-Z)",
        date: [2022, 10, 3],
        time: [13, 30],
        duration: [1, 30],
        location: "Portrait Room",
        type: "compulsory",
    },
    {
        description: "JCR Respect and Consent Workshop",
        date: [2022, 10, 3],
        time: [15, 15],
        duration: [2, 0],
        location: "Hamied Theatre",
        type: "compulsory",
    },
    {
        description: "Tutor's Pre-Dinner Social",
        date: [2022, 10, 3],
        time: [19, 0],
        duration: [0, 30],
        location: "(location on invitation)",
        type: "compulsory",
    },
    {
        description: "Matriculation Dinner (formal attire)",
        date: [2022, 10, 3],
        time: [19, 30],
        duration: [1, 30],
        location: "Formal Hall",
        type: "compulsory",
    },
    {
        description: "JCR Quiz",
        date: [2022, 10, 3],
        time: [21, 0],
        duration: [2, 0],
        location: "Formal Hall",
        type: "optional",
    },
    {
        description: "Freshers Assemble Club Night",
        date: [2022, 10, 3],
        time: [23, 0],
        duration: [3, 0],
        location: "Revolution",
        type: "optional",
    },
    // Tuesday 4th
    {
        description: "College Welfare Talk",
        date: [2022, 10, 4],
        time: [11, 30],
        duration: [0, 30],
        location: "Hamied Theatre",
        type: "compulsory",
    },
    {
        description: "Nurse's Talk",
        date: [2022, 10, 4],
        time: [12, 0],
        duration: [1, 0],
        location: "Hamied Theatre",
        type: "compulsory",
    },
    {
        description: "Christ's Freshers Fair",
        date: [2022, 10, 4],
        time: [14, 0],
        duration: [2, 0],
        location: "Plumb Auditorium",
        type: "optional",
    },
    {
        description: "Discover Cambridge Scavenger Hunt",
        date: [2022, 10, 4],
        time: [16, 0],
        duration: [2, 0],
        location: "Meet at Hobson Street car park",
        type: "optional",
    },
    {
        description: "Potential College Family Dinner",
        date: [2022, 10, 4],
        time: [18, 0],
        duration: [3, 0],
        location: "(arranged by parents)",
        type: "optional",
    },
    {
        description: "Karaoke",
        date: [2022, 10, 4],
        time: [21, 0],
        duration: [2, 0],
        location: "Buttery",
        type: "optional",
    },
    {
        description: "Glitterbomb Club Night",
        date: [2022, 10, 4],
        time: [23, 0],
        duration: [3, 0],
        location: "Vinyl",
        type: "optional",
    },
    // Wednesday 5th
    {
        description: "University Fair",
        date: [2022, 10, 5],
        time: [10, 0],
        duration: [6, 0],
        location: "Parkers Piece",
        type: "optional",
    },
    {
        description: "Subject Sibling Tours",
        date: [2022, 10, 5],
        time: [14, 0],
        duration: [3, 0],
        location: "(arranged by subject siblings)",
        type: "optional",
    },
    {
        description: "Potential College Family Dinner",
        date: [2022, 10, 5],
        time: [18, 0],
        duration: [2, 0],
        location: "(arranged by parents)",
        type: "optional",
    },
    {
        description: "Board Games and Films",
        date: [2022, 10, 5],
        time: [20, 0],
        duration: [3, 0],
        location: "JCR",
        type: "optional",
    },
    {
        description: "Rum-lola Club Night",
        date: [2022, 10, 5],
        time: [23, 0],
        duration: [3, 0],
        location: "Lola Lo",
        type: "optional",
    },
    // Thursday 6th
    {
        description: "Lectures",
        date: [2022, 10, 6],
        time: [9, 0],
        duration: [3, 0],
        location: "(check online timetable)",
        type: "compulsory",
    },
    {
        description: "Fun Fair",
        date: [2022, 10, 6],
        time: [14, 0],
        duration: [4, 0],
        location: "Fellows' Garden",
        type: "optional",
    },
    {
        description: "Choral Evensong",
        date: [2022, 10, 6],
        time: [18, 45],
        duration: [0, 30],
        location: "Fellows' Garden",
        type: "optional",
    },
    {
        description: "90's Themed Pre Party",
        date: [2022, 10, 6],
        time: [21, 0],
        duration: [2, 0],
        location: "JCR/TV Room",
        type: "optional",
    },
    {
        description: "Fleek Thursdays Club Night",
        date: [2022, 10, 6],
        time: [23, 0],
        duration: [3, 0],
        location: "Revolution",
        type: "optional",
    },
    // Friday 7th
    {
        description: "Lectures",
        date: [2022, 10, 7],
        time: [9, 0],
        duration: [3, 0],
        location: "(check online timetable)",
        type: "compulsory",
    },
    {
        description: "Coffee and Doughnuts with the Chaplain",
        date: [2022, 10, 7],
        time: [14, 0],
        duration: [2, 0],
        location: "Second Court A1",
        type: "optional",
    },
    {
        description: "JCR BBQ",
        date: [2022, 10, 7],
        time: [16, 0],
        duration: [2, 45],
        location: "(check online timetable)",
        type: "optional",
    },
    {
        description: "College Wide Bop - School Days Theme",
        date: [2022, 10, 7],
        time: [20, 0],
        duration: [3, 0],
        location: "Function Room",
        type: "optional",
    },
    // Saturday 8th
    {
        description: "Yoga",
        date: [2022, 10, 8],
        time: [11, 0],
        duration: [1, 0],
        location: "Fellows' Garden",
        type: "optional",
    },
    {
        description: "LGBTea",
        date: [2022, 10, 8],
        time: [13, 0],
        duration: [3, 0],
        location: "TV Room",
        type: "optional",
    },
    {
        description: "Subject Socials",
        date: [2022, 10, 8],
        time: [19, 0],
        duration: [2, 0],
        location: "(arranged by subject)",
        type: "optional",
    },
    // Sunday 9th
    {
        description: "Holy Communion",
        date: [2022, 10, 9],
        time: [9, 30],
        duration: [1, 0],
        location: "Chapel",
        type: "optional",
    },
    {
        description: "Picnic",
        date: [2022, 10, 9],
        time: [12, 0],
        duration: [3, 0],
        location: "Fellows' Garden",
        type: "optional",
    },
    {
        description: "Chapel Service (Evensong)",
        date: [2022, 10, 9],
        time: [18, 0],
        duration: [1, 0],
        location: "Chapel",
        type: "optional",
    },
    {
        description: "Just Dance Competition",
        date: [2022, 10, 9],
        time: [19, 0],
        duration: [1, 0],
        location: "TV Room",
        type: "optional",
    },
];