import type { Events } from "$components/events/event";

export const year: number = 2023;

export const freshers: Events<"compulsory" | "optional"> = [
    // Saturday 30th
    {
        description: "Welcome Hub",
        date: [2023, 9, 30],
        time: [9, 0],
        duration: [4, 0],
        location: "Lloyd Room",
        type: "compulsory",
    },
    {
        description: "Afternoon Meeting with your Tutor",
        date: [2023, 9, 30],
        time: [14, 0],
        duration: [2, 0],
        location: "(see letter for exact time and location)",
        type: "compulsory",
    },
    {
        description: "Meet the JCR Picnic",
        date: [2023, 9, 30],
        time: [15, 0],
        duration: [2, 0],
        location: "Fellow's Garden",
        type: "optional",
    },
    {
        description: "JCR Welfare Talk",
        date: [2023, 9, 30],
        time: [17, 0],
        duration: [0, 45],
        location: "Hamied Theatre",
        type: "compulsory",
    },
    {
        description: "Welcome Dinner (casual wear)",
        date: [2023, 9, 30],
        time: [19, 30],
        duration: [1, 30],
        location: "Formal Hall",
        type: "compulsory",
    },
    {
        description: "Initial Impressions Mixer (dress as 1st letter of name)",
        date: [2023, 9, 30],
        time: [21, 0],
        duration: [2, 0],
        location: "Function Room",
        type: "optional",
    },
    // Sunday 1st
    {
        description: "Optional Individual Matriculation Photos",
        date: [2023, 10, 1],
        time: [9, 0],
        duration: [2, 30],
        location: "First Court",
        type: "optional",
    },
    {
        description: "Group Matriculation Photo (gown & formal Attire)",
        date: [2023, 10, 1],
        time: [11, 30],
        duration: [1, 0],
        location: "Fellows' Garden",
        type: "compulsory",
    },
    {
        description: "Buy / Collect Club Wristbands",
        date: [2023, 10, 1],
        time: [13, 0],
        duration: [1, 0],
        location: "Buttery",
        type: "optional",
    },
    {
        description: "Academic Events",
        date: [2023, 10, 1],
        time: [14, 0],
        duration: [3, 30],
        location: "Hamied Theatre",
        type: "compulsory",
    },
    {
        description: "Freshers' Chapel Service",
        date: [2023, 10, 1],
        time: [18, 0],
        duration: [0, 45],
        location: "Chapel",
        type: "optional",
    },
    {
        description: "Board Games and Socialising",
        date: [2023, 10, 1],
        time: [18, 45],
        duration: [2, 15],
        location: "Box Room Café (or JCR)",
        type: "optional",
    },
    {
        description: "Pub Visit",
        date: [2023, 10, 1],
        time: [21, 0],
        duration: [2, 0],
        location: "Location TBD",
        type: "optional",
    },
    // Monday 2nd
    {
        description: "Meeting with Director of Studies",
        date: [2023, 10, 2],
        time: [9, 0],
        duration: [3, 0],
        location: "(exact time and location to be emailed)",
        type: "compulsory",
    },
    {
        description: "Matriculation Register (surnames A-K)",
        date: [2023, 10, 2],
        time: [12, 0],
        duration: [1, 30],
        location: "Portrait Room",
        type: "compulsory",
    },
    {
        description: "Matriculation Register (surnames L-Z)",
        date: [2023, 10, 2],
        time: [13, 30],
        duration: [1, 30],
        location: "Portrait Room",
        type: "compulsory",
    },
    {
        description: "College Welfare and Nurse's Talk",
        date: [2023, 10, 2],
        time: [15, 15],
        duration: [1, 0],
        location: "Hamied Theatre",
        type: "compulsory",
    },
    {
        description: "LGBTQ+ Arts and Crafts (with Kas!)",
        date: [2023, 10, 2],
        time: [16, 30],
        duration: [1, 30],
        location: "JCR",
        type: "optional",
    },
    {
        description: "Tutor's Pre-Dinner Social",
        date: [2023, 10, 2],
        time: [19, 0],
        duration: [0, 30],
        location: "(location on invitation)",
        type: "compulsory",
    },
    {
        description: "Matriculation Dinner (gown & formal attire)",
        date: [2023, 10, 2],
        time: [19, 30],
        duration: [1, 30],
        location: "Formal Hall",
        type: "compulsory",
    },
    {
        description: "Cambride & Christ's Quiz",
        date: [2023, 10, 2],
        time: [21, 0],
        duration: [1, 0],
        location: "Buttery",
        type: "optional",
    },
    {
        description: "Freshers Assemble Club Night",
        date: [2023, 10, 2],
        time: [23, 0],
        duration: [3, 0],
        location: "Revolution Cambridge",
        type: "optional",
    },
    // Tuesday 3rd
    {
        description: "University Freshers' Fair",
        date: [2023, 10, 3],
        time: [10, 0],
        duration: [6, 0],
        location: "Parker's Piece",
        type: "optional",
    },
    {
        description: "JCR Respect & Consent Workshop",
        date: [2023, 10, 3],
        time: [10, 30],
        duration: [2, 0],
        location: "Hamied Theatre",
        type: "compulsory",
    },
    {
        description: "Welfare Walk and Drop-In",
        date: [2023, 10, 3],
        time: [12, 45],
        duration: [1, 0],
        location: "Walk starts at Plodge, Drop-In at Buttery",
        type: "optional",
    },
    {
        description: "Christ's Freshers Fair",
        date: [2023, 10, 3],
        time: [14, 0],
        duration: [2, 0],
        location: "Plumb Auditorium",
        type: "optional",
    },
    {
        description: "Discover Cambridge Scavenger Hunt",
        date: [2023, 10, 3],
        time: [16, 0],
        duration: [2, 0],
        location: "Meet at Hobson Street car park",
        type: "optional",
    },
    {
        description: "College Family Dinner",
        date: [2023, 10, 3],
        time: [18, 0],
        duration: [3, 0],
        location: "(arranged by parents)",
        type: "compulsory",
    },
    {
        description: "Karaoke",
        date: [2023, 10, 3],
        time: [21, 0],
        duration: [2, 0],
        location: "Buttery",
        type: "optional",
    },
    {
        description: "Lola's Club Night",
        date: [2023, 10, 3],
        time: [23, 0],
        duration: [3, 0],
        location: "Lola Lo",
        type: "optional",
    },
    // Wednesday 4th
    {
        description: "University Freshers' Fair",
        date: [2023, 10, 4],
        time: [10, 0],
        duration: [6, 0],
        location: "Parkers Piece",
        type: "optional",
    },
    {
        description: "Discover Christ's Scavenger Hunt",
        date: [2023, 10, 4],
        time: [12, 0],
        duration: [2, 0],
        location: "Meet in Buttery",
        type: "optional",
    },
    {
        description: "Subject Sibling Tours & Advice",
        date: [2023, 10, 4],
        time: [14, 0],
        duration: [3, 0],
        location: "(arranged by subject siblings)",
        type: "optional",
    },
    {
        description: "Chill Sports Night",
        date: [2023, 10, 4],
        time: [19, 0],
        duration: [3, 0],
        location: "Kelsey Kerridge Sports Centre",
        type: "optional",
    },
    {
        description: "Rumboogie (Wednesday Revs)",
        date: [2023, 10, 4],
        time: [23, 0],
        duration: [3, 0],
        location: "Revolution Cambridge",
        type: "optional",
    },
    // Thursday 5th
    {
        description: "Lectures",
        date: [2023, 10, 5],
        time: [9, 0],
        duration: [3, 0],
        location: "(check online timetable)",
        type: "compulsory",
    },
    {
        description: "Punting",
        date: [2023, 10, 5],
        time: [14, 0],
        duration: [4, 0],
        location: "Meet at Porter's Lodge for 13:30, 14:00, or 14:30 depending on your time slot",
        type: "optional",
    },
    {
        description: "Dinner with Trinity College at Curry King",
        date: [2023, 10, 5],
        time: [18, 45],
        duration: [2, 15],
        location: "Meet at Porters' Lodge",
        type: "optional",
    },
    {
        description: "Cooking Competition",
        date: [2023, 10, 5],
        time: [19, 0],
        duration: [2, 0],
        location: "Staircases team up and will be judged by JCR members, winner announced in Buttery at 21:00",
        type: "optional",
    },
    {
        description: "Club Night Pre-Party",
        date: [2023, 10, 5],
        time: [21, 0],
        duration: [2, 0],
        location: "JCR / TV Room",
        type: "optional",
    },
    {
        description: "Naughty Noughties",
        date: [2023, 10, 5],
        time: [23, 0],
        duration: [3, 0],
        location: "Vinyl",
        type: "optional",
    },
    // Friday 6th
    {
        description: "Lectures",
        date: [2023, 10, 6],
        time: [9, 0],
        duration: [3, 0],
        location: "(check online timetable)",
        type: "compulsory",
    },
    {
        description: "Team Sports OR Cafe Hopping (tour of best cafes in Cambridge)",
        date: [2023, 10, 6],
        time: [14, 0],
        duration: [3, 0],
        location: "Meet in Buttery for both",
        type: "optional",
    },
    {
        description: "Sunset Picnic (bring drinks and snacks!)",
        date: [2023, 10, 6],
        time: [18, 0],
        duration: [2, 0],
        location: "Castle Mound",
        type: "optional",
    },
    {
        description: "College Wide Bop (theme: \"When I grow up I want to be...\")",
        date: [2023, 10, 6],
        time: [21, 30],
        duration: [3, 30],
        location: "Function Room",
        type: "optional",
    },
    // Saturday 7th
    {
        description: "Crepes and Christ's Pieces Picnic",
        date: [2023, 10, 7],
        time: [11, 0],
        duration: [2, 0],
        location: "Porter's Lodge",
        type: "optional",
    },
    {
        description: "Subject Socials (activities and food!)",
        date: [2023, 10, 7],
        time: [15, 0],
        duration: [3, 0],
        location: "Fellows Garden",
        type: "optional",
    },
    {
        description: "Disabled Students Social (run by Juno!)",
        date: [2023, 10, 7],
        time: [18, 0],
        duration: [2, 0],
        location: "JCR",
        type: "optional",
    },
    {
        description: "Movie Night (choice will be voted, some snacks provided but feel free to bring your own!)",
        date: [2023, 10, 7],
        time: [20, 0],
        duration: [3, 0],
        location: "TV Room",
        type: "optional",
    },
    // Sunday 8th
    {
        description: "Craft Social (bookmarks, room decor, and more!)",
        date: [2023, 10, 8],
        time: [13, 0],
        duration: [2, 0],
        location: "Function Room",
        type: "optional",
    },
    {
        description: "Visit Fitzwilliam Museum (it's free!)",
        date: [2023, 10, 8],
        time: [15, 45],
        duration: [2, 15],
        location: "Porter's Lodge",
        type: "optional",
    },
    {
        description: "Swap with Peterhouse",
        date: [2023, 10, 8],
        time: [19, 0],
        duration: [5, 0],
        location: "Meet at Porters' Lodge",
        type: "optional",
    },
    {
        description: "Trip to Jack's & River Stroll",
        date: [2023, 10, 8],
        time: [19, 0],
        duration: [1, 0],
        location: "Meet at Porters' Lodge",
        type: "optional",
    },
    {
        description: "End of Freshers' Week Social",
        date: [2023, 10, 8],
        time: [20, 0],
        duration: [4, 0],
        location: "JCR / TV Room",
        type: "optional",
    },
];
